### ISSUE TITLE
[FR] add ushackathonleague.com & their logo onto partners section

### ISSUE THREAD

**Issue by code-arman** [Toga-Hacks-I/Toga-Hacks-Website#11]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by SwiftWinds** [comment]
Completed in https://github.com/Toga-Hacks-I/Toga-Hacks-Website/commit/65395b5cf2a8870a277bb0e30a34fb9dd480bf21
