### ISSUE TITLE
add a "View full prospectus" button linking to the prospectus page

### ISSUE THREAD

**Issue by SwiftWinds** [Toga-Hacks-I/Toga-Hacks-Website#15]
- [x] Add subtitle "we are a registered 501(c)(3) non-profit. All donations are tax-deductible 🌱"
- [x] Add "View full prospectus" button
- [x] Put prospectus PDF on [Netlify Large Media](https://app.netlify.com/sites/togahacks/settings/large-media)
- [x] Link button to the prospectus PDF

**Comment by SwiftWinds** [comment]
Here are some next steps:

- [ ]  same margin on top and bottom and take up more viewport width
- [ ]  fix how the button looks on small to medium sized screens
- [ ]  move the PDF to Netlify large media
- [ ]  scroll lock and darken background <- I can take care of this
- [ ]  add animations to button <- I can take care of this

**Comment by MasonWang025** [comment]
Rest is yours @SwiftWinds

**Comment by SwiftWinds** [comment]
Ok. I think I can do this tomorrow

**Comment by SwiftWinds** [comment]
Tracked in https://github.com/Toga-Hacks-I/Toga-Hacks-Website/issues/36 and https://github.com/Toga-Hacks-I/Toga-Hacks-Website/issues/37
