### ISSUE TITLE
netlify large media setup for prosepctus.pdf

### ISSUE THREAD

**Issue by MasonWang025** [Toga-Hacks-I/Toga-Hacks-Website#29]
Thought I had this done @SwiftWinds, but apparently I didn't do it correctly so I'm trying again.

**Comment by SwiftWinds** [comment]
Ok, thanks :)

**Comment by MasonWang025** [comment]
@SwiftWinds git lfs is only updating to version 2.3.4. No matter how many reinstalls or updates I do, git lfs version outputs 2.3.4 (even though I downloaded 2.9.0). So netlify doesn't work with this version.
Could you give it a shot please?

**Comment by SwiftWinds** [comment]
Added in https://github.com/Toga-Hacks-I/Toga-Hacks-Website/pull/35
