### ISSUE TITLE
Remove Event Schedule buttons replace with Saturday Sunday schedules that take up full screen

### ISSUE THREAD

**Issue by HowardHuang1** [Toga-Hacks-I/Toga-Hacks-Website#49]
Currently, we have Day 1 and Day 2 buttons but we want to get rid of that so the user does not have to toggle between the days. Make the event schedule double columned so that Saturday is on the left and Sunday is on the right. Decrease the margins on left and right

**Comment by MasonWang025** [comment]
No need
